### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by MilyMilo** [Scr1ptK1tt13s/overdeer-api#22]
- [ ] Comment pagination
- [x] Consistent error messages
- [ ] Differentiate between group not found and user not authorized to perform action (404 vs 403)
- [ ] Remove comments field from get-group and list-groups routes
- [ ] Consistent ID usage 
- [ ] Update postman docs
- [ ] Write tests
